/**
 * Turn the Electron build's `src/i18n/translations.ts` into a Rust table.
 *
 * Generated rather than retyped, and generated from THEIR file rather than from a translation
 * service: these are the strings the product already ships in seven languages, reviewed by
 * whoever reviewed them. Inventing a second set would mean the two builds disagree about what
 * Rovyl says in Spanish, which is the kind of divergence nobody notices until a user reports it.
 *
 * Usage: node scripts/gen-i18n.mjs <path to translations.ts> <out.rs>
 */
import { readFileSync, writeFileSync } from 'node:fs';

const [, , source, out] = process.argv;
if (!source || !out) {
  console.error('usage: node gen-i18n.mjs <translations.ts> <out.rs>');
  process.exit(1);
}

const text = readFileSync(source, 'utf8');

/** The language tables, in the order the file declares them. */
const LANG = /^  ([a-z]{2}): \{$/gm;
const starts = [];
let match;
while ((match = LANG.exec(text))) {
  starts.push({ code: match[1], at: match.index });
}
if (starts.length === 0) {
  console.error('no language tables found');
  process.exit(1);
}

/**
 * One table's entries.
 *
 * The values are single-quoted TypeScript strings which may contain an escaped quote. Template
 * literals and expressions are refused rather than mangled: a key whose value is computed is a key
 * this table cannot carry, and silently emitting the source text would put `${count}` on screen.
 */
function entriesOf(body) {
  const found = new Map();
  const ENTRY = /^    ([a-zA-Z0-9_]+):\s*(.+?),?\s*$/gm;
  let entry;
  while ((entry = ENTRY.exec(body))) {
    const [, key, raw] = entry;
    const value = raw.replace(/,\s*$/, '').trim();
    if (!value.startsWith("'") && !value.startsWith('"')) {
      console.warn(`skipping ${key}: not a plain string (${value.slice(0, 40)})`);
      continue;
    }
    const quote = value[0];
    if (!value.endsWith(quote)) {
      console.warn(`skipping ${key}: spans lines`);
      continue;
    }
    // Unescape only what a single-quoted TS string can carry.
    const inner = value
      .slice(1, -1)
      .replace(/\\'/g, "'")
      .replace(/\\"/g, '"')
      .replace(/\\\\/g, '\\');
    found.set(key, inner);
  }
  return found;
}

const tables = new Map();
for (let index = 0; index < starts.length; index += 1) {
  const from = starts[index].at;
  const to = index + 1 < starts.length ? starts[index + 1].at : text.length;
  tables.set(starts[index].code, entriesOf(text.slice(from, to)));
}

const codes = [...tables.keys()];
const english = tables.get('en');
if (!english) {
  console.error('no `en` table');
  process.exit(1);
}

// Key parity is the thing worth failing on. A table missing a key falls back to English at
// runtime, which is correct behaviour and a silent hole in a translation.
const keys = [...english.keys()].sort();
for (const [code, table] of tables) {
  const missing = keys.filter((key) => !table.has(key));
  if (missing.length) {
    console.warn(`${code} is missing ${missing.length} keys: ${missing.slice(0, 5).join(', ')}…`);
  }
}

const esc = (s) => s.replace(/\\/g, '\\\\').replace(/"/g, '\\"');

const rows = keys
  .map((key) => {
    const values = codes.map((code) => `"${esc(tables.get(code).get(key) ?? '')}"`);
    return `    Entry {\n        key: "${key}",\n        values: &[${values.join(', ')}],\n    },`;
  })
  .join('\n');

const body = `//! The settings panel's text, in the languages the product ships.
//!
//! GENERATED by \`scripts/gen-i18n.mjs\` from the Electron build's \`src/i18n/translations.ts\`.
//! Do not edit by hand: edit that file and run the script, so the two builds never disagree about
//! what Rovyl says in Spanish.
//!
//! The coverage matches the original's, which is deliberate rather than partial: the nav, the
//! common verbs and the workspace editor's labels are translated there, and the row descriptions
//! are not. Translating more here than the original translates would make the two panels say
//! different things to the same user.
//!
//! ${codes.length} languages, ${keys.length} keys.

use super::strings::Entry;

/// The order the values are in, which is \`i18n::LANGUAGES\` order.
pub const CODES: &[&str] = &[${codes.map((c) => `"${c}"`).join(', ')}];

pub const SETTINGS: &[Entry] = &[
${rows}
];
`;

writeFileSync(out, body);
console.log(
  `${keys.length} keys x ${codes.length} languages (${codes.join(', ')}) -> ${out}`,
);
