//! The settings panel's text, in the languages the product ships.
//!
//! GENERATED by `scripts/gen-i18n.mjs` from the Electron build's `src/i18n/translations.ts`.
//! Do not edit by hand: edit that file and run the script, so the two builds never disagree about
//! what Rovyl says in Spanish.
//!
//! The coverage matches the original's, which is deliberate rather than partial: the nav, the
//! common verbs and the workspace editor's labels are translated there, and the row descriptions
//! are not. Translating more here than the original translates would make the two panels say
//! different things to the same user.
//!
//! 7 languages, 106 keys.

use super::strings::Entry;

/// The order the values are in, which is `i18n::LANGUAGES` order.
pub const CODES: &[&str] = &["en", "es", "zh", "pt", "ru", "de", "ar"];

pub const SETTINGS: &[Entry] = &[
    Entry {
        key: "add",
        values: &["Add", "Añadir", "添加", "Adicionar", "Добавить", "Hinzufügen", "إضافة"],
    },
    Entry {
        key: "addSelected",
        values: &["Add Selected", "Añadir selección", "添加所选", "Adicionar selecionados", "Добавить выбранное", "Auswahl hinzufügen", "إضافة المحدد"],
    },
    Entry {
        key: "addShortcut",
        values: &["Add shortcut", "Añadir acceso directo", "添加快捷方式", "Adicionar atalho", "Добавить ярлык", "Verknüpfung hinzufügen", "إضافة اختصار"],
    },
    Entry {
        key: "address",
        values: &["Address", "Dirección", "地址", "Endereço", "Адрес", "Adresse", "العنوان / الرابط"],
    },
    Entry {
        key: "advanced",
        values: &["Advanced", "Avanzado", "高级", "Avançado", "Дополнительно", "Erweitert", "خيارات متقدمة"],
    },
    Entry {
        key: "advancedDesc",
        values: &["Protection, shortcuts, and data.", "Protección, atajos y datos.", "保护、快捷方式与数据。", "Proteção, atalhos e dados.", "Защита, быстрые клавиши и данные.", "Schutz, Tastenkürzel und Daten.", "الحماية، الاختصارات، والبيانات."],
    },
    Entry {
        key: "alreadySelected",
        values: &["Already selected", "Ya seleccionado", "已添加", "Já selecionado", "Уже добавлено", "Bereits ausgewählt", "محدد مسبقاً"],
    },
    Entry {
        key: "angleAim",
        values: &["Angle (direction)", "Ángulo (dirección)", "角度（方向）", "Ângulo (direção)", "Угол (направление)", "Winkel (Richtung)", "الزاوية (الاتجاه)"],
    },
    Entry {
        key: "appearance",
        values: &["Appearance", "Apariencia", "外观", "Aparência", "Внешний вид", "Darstellung", "المظهر والسمة"],
    },
    Entry {
        key: "appearanceDesc",
        values: &["Shape, presence, and theme.", "Forma, presencia y tema.", "形状、呈现方式与主题。", "Forma, presença e tema.", "Форма, отображение и тема.", "Form, Präsenz und Design.", "الشكل، التعتيم، والسمة."],
    },
    Entry {
        key: "application",
        values: &["Application", "Aplicación", "应用程序", "Aplicativo", "Приложение", "Anwendung", "تطبيق"],
    },
    Entry {
        key: "appsCount",
        values: &["applications", "aplicaciones", "个应用", "aplicativos", "приложений", "Anwendungen", "تطبيقات"],
    },
    Entry {
        key: "available",
        values: &["Available", "Disponible", "可用", "Disponível", "Доступно", "Verfügbar", "متاحة"],
    },
    Entry {
        key: "availableOnWheel",
        values: &["Available on the wheel", "Disponible en la rueda", "在轮盘上可用", "Disponível na roda", "Доступно на колесе", "Auf dem Rad verfügbar", "متاح على العجلة"],
    },
    Entry {
        key: "back",
        values: &["Back", "Atrás", "返回", "Voltar", "Назад", "Zurück", "رجوع"],
    },
    Entry {
        key: "battery",
        values: &["Battery", "Batería", "电池", "Bateria", "Батарея", "Akku", "البطارية"],
    },
    Entry {
        key: "bgDimming",
        values: &["Background dimming", "Atenuación del fondo", "背景变暗", "Escurecimento do fundo", "Затемнение фона", "Hintergrund abdunkeln", "تعتيم الخلفية"],
    },
    Entry {
        key: "bgDimmingDesc",
        values: &["How much the rest of the screen recedes. At 100% the desktop is covered edge to edge.", "Cuánto se difumina el resto de la pantalla. Al 100 % el escritorio queda cubierto por completo.", "屏幕其余部分的变暗程度。100% 时桌面被完全遮盖。", "O quanto o resto da tela recua. Em 100% a área de trabalho fica totalmente coberta.", "Насколько отступает остальной экран. При 100 % рабочий стол закрыт полностью.", "Wie stark der restliche Bildschirm zurücktritt. Bei 100 % ist der Desktop vollständig verdeckt.", "درجة تعتيم الشاشة خلف العجلة. عند 100% يتم تغطية سطح المكتب بالكامل."],
    },
    Entry {
        key: "btnMiddle",
        values: &["Middle button", "Botón central", "中键", "Botão do meio", "Средняя кнопка", "Mittlere Taste", "الزر الأوسط (العجلة)"],
    },
    Entry {
        key: "btnX1",
        values: &["Mouse button 4 (Back)", "Botón 4 del ratón (Atrás)", "鼠标按键 4（后退）", "Botão 4 do mouse (Voltar)", "Кнопка мыши 4 (Назад)", "Maustaste 4 (Zurück)", "زر الفأرة الجانبي 4 (للخلف)"],
    },
    Entry {
        key: "btnX2",
        values: &["Mouse button 5 (Forward)", "Botón 5 del ratón (Adelante)", "鼠标按键 5（前进）", "Botão 5 do mouse (Avançar)", "Кнопка мыши 5 (Вперёд)", "Maustaste 5 (Vor)", "زر الفأرة الجانبي 5 (للأمام)"],
    },
    Entry {
        key: "cancel",
        values: &["Cancel", "Cancelar", "取消", "Cancelar", "Отмена", "Abbrechen", "إلغاء"],
    },
    Entry {
        key: "center",
        values: &["Center", "Centro", "中心", "Centro", "Центр", "Mitte", "المركز"],
    },
    Entry {
        key: "change",
        values: &["Change", "Cambiar", "更改", "Alterar", "Изменить", "Ändern", "تغيير"],
    },
    Entry {
        key: "chooseFile",
        values: &["Choose file", "Elegir archivo", "选择文件", "Escolher arquivo", "Выбрать файл", "Datei auswählen", "اختيار ملف يدوي"],
    },
    Entry {
        key: "clearSelection",
        values: &["Clear selection", "Borrar selección", "清除选择", "Limpar seleção", "Снять выделение", "Auswahl aufheben", "إلغاء التحديد"],
    },
    Entry {
        key: "clock",
        values: &["Clock", "Reloj", "时钟", "Relógio", "Часы", "Uhr", "الساعة"],
    },
    Entry {
        key: "close",
        values: &["Close", "Cerrar", "关闭", "Fechar", "Закрыть", "Schließen", "إغلاق"],
    },
    Entry {
        key: "confirmReset",
        values: &["Are you sure you want to reset all settings to defaults?", "¿Seguro que quieres restablecer todos los ajustes a sus valores predeterminados?", "确定要将所有设置恢复为默认值吗？", "Tem certeza de que deseja redefinir todas as configurações para os valores padrão?", "Сбросить все настройки к значениям по умолчанию?", "Möchtest du wirklich alle Einstellungen auf die Standardwerte zurücksetzen?", "هل أنت متأكد من رغبتك في استعادة الإعدادات الافتراضية؟"],
    },
    Entry {
        key: "create",
        values: &["Create", "Crear", "新建", "Criar", "Создать", "Erstellen", "إنشاء"],
    },
    Entry {
        key: "current",
        values: &["Current", "Actual", "当前", "Atual", "Текущее", "Aktuell", "الحالية"],
    },
    Entry {
        key: "cursorAim",
        values: &["Cursor (hover item)", "Cursor (pasar por encima)", "光标（悬停选中）", "Cursor (passar sobre o item)", "Курсор (наведение на элемент)", "Zeiger (Eintrag überfahren)", "المؤشر (التحويم فوق العنصر)"],
    },
    Entry {
        key: "delete",
        values: &["Delete", "Eliminar", "删除", "Excluir", "Удалить", "Löschen", "حذف"],
    },
    Entry {
        key: "deleteWorkspace",
        values: &["Delete workspace", "Eliminar espacio de trabajo", "删除工作区", "Excluir espaço de trabalho", "Удалить рабочее пространство", "Arbeitsbereich löschen", "حذف مساحة العمل"],
    },
    Entry {
        key: "done",
        values: &["Done", "Listo", "完成", "Concluído", "Готово", "Fertig", "تم"],
    },
    Entry {
        key: "folder",
        values: &["Folder", "Carpeta", "文件夹", "Pasta", "Папка", "Ordner", "مجلد"],
    },
    Entry {
        key: "folderPath",
        values: &["Folder path", "Ruta de la carpeta", "文件夹路径", "Caminho da pasta", "Путь к папке", "Ordnerpfad", "مسار المجلد"],
    },
    Entry {
        key: "general",
        values: &["General", "General", "常规", "Geral", "Основное", "Allgemein", "عام"],
    },
    Entry {
        key: "generalDesc",
        values: &["Core Rovyl behavior.", "Comportamiento básico de Rovyl.", "Rovyl 的核心行为。", "Comportamento básico do Rovyl.", "Базовое поведение Rovyl.", "Grundlegendes Verhalten von Rovyl.", "سلوك Rovyl الأساسي والنظام."],
    },
    Entry {
        key: "gestureBehavior",
        values: &["Gesture behavior", "Comportamiento del gesto", "手势行为", "Comportamento do gesto", "Поведение жеста", "Gestenverhalten", "سلوك الإيماءة"],
    },
    Entry {
        key: "gestureBehaviorDesc",
        values: &["How middle-click triggers the radial menu.", "Cómo abre el menú radial el clic central.", "中键点击触发径向菜单的方式。", "Como o clique do botão do meio abre o menu radial.", "Как нажатие средней кнопки открывает радиальное меню.", "Wie ein Klick mit der mittleren Maustaste das Radialmenü öffnet.", "طريقة فتح القائمة الدائرية بالنقر بالزر الأوسط."],
    },
    Entry {
        key: "globalShortcut",
        values: &["Global shortcut", "Atajo global", "全局快捷键", "Atalho global", "Глобальное сочетание", "Globales Tastenkürzel", "الاختصار العام (لوحة المفاتيح أو الفأرة)"],
    },
    Entry {
        key: "globalShortcutDesc",
        values: &["Keyboard or mouse shortcut to summon the radial menu anywhere.", "Atajo de teclado o ratón para abrir el menú radial en cualquier sitio.", "在任何位置唤出径向菜单的键盘或鼠标快捷键。", "Atalho de teclado ou mouse para chamar o menu radial em qualquer lugar.", "Сочетание клавиш или кнопка мыши для вызова радиального меню в любом месте.", "Tasten- oder Mauskürzel, das das Radialmenü überall aufruft.", "الاختصار المستخدم لاستدعاء القائمة في أي مكان بالنظام بواسطة المفاتيح أو أزرار الفأرة."],
    },
    Entry {
        key: "installedApp",
        values: &["Installed application", "Aplicación instalada", "已安装的应用", "Aplicativo instalado", "Установленное приложение", "Installierte Anwendung", "تطبيق مثبت"],
    },
    Entry {
        key: "language",
        values: &["Language", "Idioma", "语言", "Idioma", "Язык", "Sprache", "اللغة / Language"],
    },
    Entry {
        key: "languageDesc",
        values: &["Choose interface display language.", "Elige el idioma de la interfaz.", "选择界面显示语言。", "Escolha o idioma da interface.", "Выберите язык интерфейса.", "Sprache der Benutzeroberfläche wählen.", "اختر لغة عرض واجهة التطبيق."],
    },
    Entry {
        key: "launchMode",
        values: &["Launch mode", "Modo de apertura", "启动方式", "Modo de abertura", "Режим запуска", "Startmodus", "نمط التشغيل"],
    },
    Entry {
        key: "launchNormal",
        values: &["Normal", "Normal", "普通", "Normal", "Обычный", "Normal", "عادي"],
    },
    Entry {
        key: "launchReuse",
        values: &["Reuse", "Reutilizar", "复用窗口", "Reutilizar", "Повторное использование", "Wiederverwenden", "إعادة استخدام النافذة"],
    },
    Entry {
        key: "launchWarm",
        values: &["Warm", "Precargado", "预热", "Pré-carregado", "Предзапуск", "Vorgeladen", "تسريع مسبق"],
    },
    Entry {
        key: "loadingApps",
        values: &["Loading applications…", "Cargando aplicaciones…", "正在加载应用…", "Carregando aplicativos…", "Загрузка приложений…", "Anwendungen werden geladen…", "جاري تحميل التطبيقات…"],
    },
    Entry {
        key: "makeCurrent",
        values: &["Make current workspace", "Usar como espacio actual", "设为当前工作区", "Definir como espaço atual", "Сделать текущим", "Als aktuellen Arbeitsbereich festlegen", "تعيين كمساحة عمل حالية"],
    },
    Entry {
        key: "mouse",
        values: &["Mouse", "Ratón", "鼠标", "Mouse", "Мышь", "Maus", "الفأرة"],
    },
    Entry {
        key: "mouseButton",
        values: &["Trigger mouse button", "Botón del ratón", "触发鼠标按钮", "Botão do mouse", "Кнопка мыши", "Auslösende Maustaste", "زر الفأرة المشغّل"],
    },
    Entry {
        key: "mouseButtonDesc",
        values: &["Which mouse button summons the wheel.", "Qué botón del ratón abre la rueda.", "用哪个鼠标按钮唤出轮盘。", "Qual botão do mouse chama a roda.", "Какая кнопка мыши вызывает колесо.", "Welche Maustaste das Rad aufruft.", "زر الفأرة المخصص لاستدعاء العجلة الدائرية."],
    },
    Entry {
        key: "mouseClick",
        values: &["Click to open", "Clic para abrir", "点击打开", "Clicar para abrir", "Нажатие для открытия", "Klicken zum Öffnen", "نقر للفتح/الإغلاق"],
    },
    Entry {
        key: "mouseHold",
        values: &["Hold to open", "Mantener para abrir", "按住打开", "Segurar para abrir", "Удержание для открытия", "Gedrückt halten zum Öffnen", "ضغط مطول (إفلات للتشغيل)"],
    },
    Entry {
        key: "multiSelect",
        values: &["Multi-select", "Selección múltiple", "多选", "Seleção múltipla", "Множественный выбор", "Mehrfachauswahl", "تحديد متعدد"],
    },
    Entry {
        key: "name",
        values: &["Name", "Nombre", "名称", "Nome", "Название", "Name", "الاسم"],
    },
    Entry {
        key: "newWorkspace",
        values: &["New workspace", "Nuevo espacio de trabajo", "新建工作区", "Novo espaço de trabalho", "Новое рабочее пространство", "Neuer Arbeitsbereich", "مساحة عمل جديدة"],
    },
    Entry {
        key: "newWorkspaceDesc",
        values: &["Create another context for your shortcuts.", "Crea otro contexto para tus accesos directos.", "为快捷方式创建另一个场景。", "Crie outro contexto para seus atalhos.", "Создайте ещё один контекст для ярлыков.", "Einen weiteren Kontext für deine Verknüpfungen anlegen.", "إنشاء سياق آخر لتنظيم اختصاراتك وتطبيقاتك."],
    },
    Entry {
        key: "noAppsFound",
        values: &["No applications found.", "No se encontraron aplicaciones.", "未找到应用程序。", "Nenhum aplicativo encontrado.", "Приложения не найдены.", "Keine Anwendungen gefunden.", "لم يتم العثور على تطبيقات."],
    },
    Entry {
        key: "openAtLogin",
        values: &["Run at startup", "Iniciar con Windows", "开机自启动", "Iniciar com o Windows", "Запускать вместе с Windows", "Mit Windows starten", "تشغيل تلقائي مع الويندوز"],
    },
    Entry {
        key: "openAtLoginDesc",
        values: &["Start Rovyl automatically when Windows boots up.", "Abre Rovyl automáticamente al arrancar Windows.", "Windows 启动时自动运行 Rovyl。", "Abre o Rovyl automaticamente quando o Windows é iniciado.", "Запускать Rovyl автоматически при загрузке Windows.", "Rovyl automatisch beim Start von Windows ausführen.", "بدء تشغيل التطبيق في الخلفية تلقائياً فور إقلاع النظام."],
    },
    Entry {
        key: "paused",
        values: &["Paused", "En pausa", "已暂停", "Pausado", "Приостановлено", "Pausiert", "متوقفة"],
    },
    Entry {
        key: "persistentLabels",
        values: &["Persistent labels", "Etiquetas permanentes", "始终显示名称", "Rótulos sempre visíveis", "Всегда показывать названия", "Beschriftungen dauerhaft anzeigen", "إظهار الأسماء دائماً"],
    },
    Entry {
        key: "persistentLabelsDesc",
        values: &["Keep every target name visible on the wheel.", "Mantén visible el nombre de cada elemento de la rueda.", "在轮盘上始终显示每个项目的名称。", "Mantenha o nome de cada item visível na roda.", "Показывать название каждого элемента на колесе.", "Den Namen jedes Eintrags immer auf dem Rad anzeigen.", "إبقاء أسماء كافة التطبيقات ظاهرة على العجلة."],
    },
    Entry {
        key: "presence",
        values: &["Presence", "Presencia", "呈现", "Presença", "Отображение", "Präsenz", "المظهر والخلفية"],
    },
    Entry {
        key: "recordShortcut",
        values: &["Record shortcut", "Grabar atajo", "录制快捷键", "Gravar atalho", "Записать сочетание", "Kürzel aufzeichnen", "تسجيل اختصار"],
    },
    Entry {
        key: "recording",
        values: &["Press keys or mouse button…", "Pulsa teclas o un botón del ratón…", "请按下按键或鼠标按钮…", "Pressione teclas ou um botão do mouse…", "Нажмите клавиши или кнопку мыши…", "Tasten oder Maustaste drücken…", "اضغط مفتاحاً أو زر فأرة…"],
    },
    Entry {
        key: "reload",
        values: &["Reload", "Recargar", "重新加载", "Recarregar", "Обновить", "Neu laden", "إعادة تحميل"],
    },
    Entry {
        key: "reloadList",
        values: &["Reload list", "Recargar lista", "刷新列表", "Recarregar lista", "Обновить список", "Liste neu laden", "تحديث القائمة"],
    },
    Entry {
        key: "reset",
        values: &["Reset", "Restablecer", "重置", "Redefinir", "Сбросить", "Zurücksetzen", "إعادة ضبط"],
    },
    Entry {
        key: "resetAll",
        values: &["Reset all settings", "Restablecer todos los ajustes", "重置所有设置", "Redefinir todas as configurações", "Сбросить все настройки", "Alle Einstellungen zurücksetzen", "إعادة ضبط كافة الإعدادات"],
    },
    Entry {
        key: "resetDesc",
        values: &["Restore all configurations to their default values.", "Devuelve toda la configuración a sus valores predeterminados.", "将所有配置恢复为默认值。", "Restaura todas as configurações para os valores padrão.", "Вернуть все параметры к значениям по умолчанию.", "Setzt alle Einstellungen auf die Standardwerte zurück.", "استعادة جميع الإعدادات إلى القيم الافتراضية الأصلية."],
    },
    Entry {
        key: "save",
        values: &["Save", "Guardar", "保存", "Salvar", "Сохранить", "Speichern", "حفظ"],
    },
    Entry {
        key: "searchApps",
        values: &["Search installed applications", "Buscar aplicaciones instaladas", "搜索已安装的应用", "Buscar aplicativos instalados", "Поиск установленных приложений", "Installierte Anwendungen durchsuchen", "بحث في التطبيقات المثبتة"],
    },
    Entry {
        key: "searchSettings",
        values: &["Search settings", "Buscar ajustes", "搜索设置", "Buscar configurações", "Поиск по настройкам", "Einstellungen durchsuchen", "البحث في الإعدادات"],
    },
    Entry {
        key: "selectAll",
        values: &["Select all", "Seleccionar todo", "全选", "Selecionar tudo", "Выбрать все", "Alle auswählen", "تحديد الكل"],
    },
    Entry {
        key: "selectedCount",
        values: &["selected", "seleccionados", "已选择", "selecionados", "выбрано", "ausgewählt", "محدد"],
    },
    Entry {
        key: "selectionMode",
        values: &["Selection mode", "Modo de selección", "选择方式", "Modo de seleção", "Способ выбора", "Auswahlmodus", "نمط التحديد"],
    },
    Entry {
        key: "selectionModeDesc",
        values: &["How the cursor points to wheel slices.", "Cómo apunta el cursor a los sectores de la rueda.", "光标指向轮盘扇区的方式。", "Como o cursor aponta para as fatias da roda.", "Как курсор указывает на секторы колеса.", "Wie der Zeiger auf die Segmente des Rads zielt.", "طريقة توجيه المؤشر لاختيار عناصر العجلة."],
    },
    Entry {
        key: "settings",
        values: &["Settings", "Ajustes", "设置", "Configurações", "Настройки", "Einstellungen", "الإعدادات"],
    },
    Entry {
        key: "shortcutBehavior",
        values: &["Shortcut behavior", "Comportamiento del atajo", "快捷键行为", "Comportamento do atalho", "Поведение сочетания клавиш", "Verhalten des Tastenkürzels", "سلوك اختصار الكيبورد"],
    },
    Entry {
        key: "shortcutBehaviorDesc",
        values: &["How the global keyboard shortcut activates the menu.", "Cómo activa el menú el atajo de teclado global.", "全局快捷键唤出菜单的方式。", "Como o atalho global de teclado ativa o menu.", "Как глобальное сочетание клавиш вызывает меню.", "Wie das globale Tastenkürzel das Menü aufruft.", "طريقة عمل الاختصار العام لفتح القائمة."],
    },
    Entry {
        key: "shortcutHold",
        values: &["Hold", "Mantener", "按住", "Segurar", "Удержание", "Halten", "ضغط مطول"],
    },
    Entry {
        key: "shortcutHoldHelp",
        values: &["Hold the shortcut to keep the wheel up, and release it to launch whatever you are aiming at.", "Mantén pulsado el atajo para ver la rueda y suéltalo para abrir aquello a lo que apuntas.", "按住快捷键查看轮盘，松开即可启动所指向的项目。", "Segure o atalho para ver a roda e solte para abrir aquilo que estiver apontado.", "Удерживайте сочетание, чтобы видеть колесо, и отпустите, чтобы запустить выбранное.", "Halte das Kürzel gedrückt, um das Rad zu sehen, und lass los, um das Anvisierte zu starten.", "استمر بالضغط على الاختصار لرؤية العجلة، وأفلته لتشغيل ما وجّهته إليه."],
    },
    Entry {
        key: "shortcutToggle",
        values: &["Toggle", "Alternar", "切换", "Alternar", "Переключение", "Umschalten", "تبديل"],
    },
    Entry {
        key: "shortcutToggleHelp",
        values: &["Press the shortcut once to open the wheel, and again to close it.", "Pulsa el atajo una vez para abrir la rueda y otra vez para cerrarla.", "按一次快捷键打开轮盘，再按一次关闭。", "Pressione o atalho uma vez para abrir a roda e outra vez para fechá-la.", "Нажмите сочетание один раз, чтобы открыть колесо, и ещё раз, чтобы закрыть его.", "Einmal drücken öffnet das Rad, noch einmal drücken schließt es.", "اضغط الاختصار مرة لفتح العجلة، ومرة أخرى لإغلاقها."],
    },
    Entry {
        key: "shortcuts",
        values: &["Shortcuts", "Accesos directos", "快捷方式", "Atalhos", "Ярлыки", "Verknüpfungen", "الاختصارات"],
    },
    Entry {
        key: "shortcutsTitle",
        values: &["Shortcuts", "Accesos directos", "快捷方式", "Atalhos", "Ярлыки", "Verknüpfungen", "الاختصارات والتطبيقات"],
    },
    Entry {
        key: "singleSelect",
        values: &["Single select", "Selección única", "单选", "Seleção única", "Одиночный выбор", "Einzelauswahl", "تحديد فردي"],
    },
    Entry {
        key: "sound",
        values: &["Sound", "Sonido", "声音", "Som", "Звук", "Ton", "الصوت"],
    },
    Entry {
        key: "soundDesc",
        values: &["Notes for opening and moving around the wheel.", "Notas al abrir la rueda y moverte por ella.", "打开轮盘和在其中移动时的提示音。", "Notas ao abrir a roda e mover-se por ela.", "Звуки при открытии колеса и перемещении по нему.", "Töne beim Öffnen des Rads und beim Bewegen darin.", "نغمات عند فتح القائمة الدائرية والتنقل فيها."],
    },
    Entry {
        key: "target",
        values: &["Target", "Destino", "目标", "Destino", "Целевой путь", "Ziel", "المسار المستهدف"],
    },
    Entry {
        key: "trigger",
        values: &["Activation", "Activación", "激活方式", "Ativação", "Активация", "Aktivierung", "التفعيل والتشغيل"],
    },
    Entry {
        key: "triggerDesc",
        values: &["How and where the wheel appears.", "Cómo y dónde aparece la rueda.", "轮盘出现的方式和位置。", "Como e onde a roda aparece.", "Как и где появляется колесо.", "Wie und wo das Rad erscheint.", "طريقة وموقع ظهور القائمة الدائرية."],
    },
    Entry {
        key: "tryAgain",
        values: &["Try again", "Reintentar", "重试", "Tentar novamente", "Повторить", "Erneut versuchen", "حاول مجدداً"],
    },
    Entry {
        key: "updates",
        values: &["Updates", "Actualizaciones", "更新", "Atualizações", "Обновления", "Updates", "التحديثات"],
    },
    Entry {
        key: "url",
        values: &["URL", "URL", "网址", "URL", "Ссылка", "URL", "رابط ويب"],
    },
    Entry {
        key: "weather",
        values: &["Weather", "Tiempo", "天气", "Clima", "Погода", "Wetter", "الطقس"],
    },
    Entry {
        key: "wheel",
        values: &["Wheel", "Rueda", "轮盘", "Roda", "Колесо", "Rad", "العجلة"],
    },
    Entry {
        key: "workspaceName",
        values: &["Workspace name", "Nombre del espacio", "工作区名称", "Nome do espaço de trabalho", "Название пространства", "Name des Arbeitsbereichs", "اسم مساحة العمل"],
    },
    Entry {
        key: "workspaces",
        values: &["Workspaces", "Espacios de trabajo", "工作区", "Espaços de trabalho", "Рабочие пространства", "Arbeitsbereiche", "مساحات العمل"],
    },
    Entry {
        key: "workspacesDesc",
        values: &["Contexts and their shortcuts.", "Contextos y sus accesos directos.", "各个场景及其快捷方式。", "Contextos e seus atalhos.", "Контексты и их ярлыки.", "Kontexte und ihre Verknüpfungen.", "سياقات العمل وقوائم التطبيقات."],
    },
    Entry {
        key: "yourWorkspaces",
        values: &["Your workspaces", "Tus espacios de trabajo", "你的工作区", "Seus espaços de trabalho", "Ваши рабочие пространства", "Deine Arbeitsbereiche", "مساحات العمل لديك"],
    },
];
