"use strict";

const { describe, it } = require("node:test");
const assert = require("node:assert");
const fs = require("fs");
const os = require("os");
const path = require("path");
const {
  splitWin32SpawnExeAndArgs,
  canonicalizeWin32LaunchCommand,
  appsFolderAppId,
  isAppsFolderCommand,
  toAppsFolderCommand,
  looksLikeBareStartAppId,
} = require("./win32-launch.js");

/**
 * Real `Get-StartApps` output, copied from a live Windows 10 host. The shapes are the point: every
 * one of these is a valid `shell:AppsFolder` entry (checked against the shell namespace), and all
 * but the last two are useless as a command line.
 */
const START_APP_IDS = {
  figmaSquirrel: "com.squirrel.Figma.Figma",
  capcutFlattenedPath: "c:.users.arshit.appdata.local.capcut.apps.9.5.0.4045.capcut.exe",
  zoomWithSpaces: "zoom.us.Zoom Video Meetings",
  vlcKnownFolder: "{7C5A40EF-A0FB-4BFC-874A-C0F2E0B9FA8E}\\VideoLAN\\VLC\\vlc.exe",
  calculatorAumid: "Microsoft.WindowsCalculator_8wekyb3d8bbwe!App",
  chromeAlias: "Chrome",
  subnauticaRealPath: "C:\\Games\\Subnautica\\Subnautica.exe",
};

describe("win32-launch", () => {
  it("splits Program Files style path + args using real file on disk", () => {
    if (process.platform !== "win32") return;
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), "zenith-launch-"));
    const exe = path.join(dir, "sub dir", "fakeapp.exe");
    fs.mkdirSync(path.dirname(exe), { recursive: true });
    fs.writeFileSync(exe, "");
    try {
      const line = `${exe} --foo bar`;
      const { exe: e, args } = splitWin32SpawnExeAndArgs(line);
      assert.strictEqual(e, exe);
      assert.deepStrictEqual(args, ["--foo", "bar"]);
      const canon = canonicalizeWin32LaunchCommand(line);
      assert(canon.startsWith('"'), "canonicalized exe should be quoted");
      assert(canon.includes("--foo"));
    } finally {
      try {
        fs.rmSync(dir, { recursive: true, force: true });
      } catch (_) {}
    }
  });

  it("leaves internal: and https URLs unchanged", () => {
    assert.strictEqual(
      canonicalizeWin32LaunchCommand("internal:notes"),
      "internal:notes",
    );
    assert.strictEqual(
      canonicalizeWin32LaunchCommand("https://example.com/a b"),
      "https://example.com/a b",
    );
  });
});

describe("AppsFolder launch lines", () => {
  it("wraps every Start menu AppID except the ones that are already paths", () => {
    assert.strictEqual(
      toAppsFolderCommand(START_APP_IDS.figmaSquirrel),
      "shell:AppsFolder\\com.squirrel.Figma.Figma",
    );
    /** An id with spaces is still ONE id: nothing here may split it. */
    assert.strictEqual(
      toAppsFolderCommand(START_APP_IDS.zoomWithSpaces),
      "shell:AppsFolder\\zoom.us.Zoom Video Meetings",
    );
    /** Idempotent: re-adding an app that is already stored as a moniker must not double the prefix. */
    const once = toAppsFolderCommand(START_APP_IDS.calculatorAumid);
    assert.strictEqual(toAppsFolderCommand(once), once);
  });

  it("reads the id back whole, spaces and known-folder GUIDs included", () => {
    assert.strictEqual(
      appsFolderAppId(toAppsFolderCommand(START_APP_IDS.zoomWithSpaces)),
      START_APP_IDS.zoomWithSpaces,
    );
    assert.strictEqual(
      appsFolderAppId(toAppsFolderCommand(START_APP_IDS.vlcKnownFolder)),
      START_APP_IDS.vlcKnownFolder,
    );
    assert.strictEqual(appsFolderAppId("shell:appsfolder/Chrome"), "Chrome");
    assert.strictEqual(appsFolderAppId(START_APP_IDS.figmaSquirrel), null);
    assert.strictEqual(appsFolderAppId("C:\\Windows\\notepad.exe"), null);
    assert.ok(isAppsFolderCommand(toAppsFolderCommand(START_APP_IDS.chromeAlias)));
    assert.ok(!isAppsFolderCommand(START_APP_IDS.subnauticaRealPath));
  });

  it("recognises a bare AppID stored before the picker wrote monikers", () => {
    /**
     * These are the shortcuts already sitting in people's workspaces. Recognising them by shape is
     * what makes them launch again without rewriting anyone's config.
     */
    for (const id of [
      START_APP_IDS.figmaSquirrel,
      START_APP_IDS.capcutFlattenedPath,
      START_APP_IDS.zoomWithSpaces,
      START_APP_IDS.vlcKnownFolder,
      START_APP_IDS.calculatorAumid,
      "Microsoft.AutoGenerated.{153C632B-EAE8-4242-71B2-A22CBB429288}",
    ]) {
      assert.ok(looksLikeBareStartAppId(id), `should be read as an AppID: ${id}`);
    }
  });

  it("does not mistake a real launch line for an AppID", () => {
    /**
     * `notepad.exe` is NOT an AppsFolder entry on a live host, and `Chrome` is one but is
     * indistinguishable from a plain command name — both keep running through `start`, which already
     * works for them. Claiming either would trade a working launch for a guess.
     */
    for (const line of [
      START_APP_IDS.subnauticaRealPath,
      START_APP_IDS.chromeAlias,
      "notepad",
      "notepad.exe",
      '"C:\\Program Files\\App\\app.exe" --flag',
      "C:\\Program Files\\Microsoft VS Code\\Code.exe",
      "\\\\server\\share\\tool.exe",
      "https://example.com",
      "internal:notes",
      "shortcut:Ctrl+Shift+S",
      "shell:AppsFolder\\com.squirrel.Figma.Figma",
    ]) {
      assert.ok(!looksLikeBareStartAppId(line), `should NOT be read as an AppID: ${line}`);
    }
  });

  it("keeps monikers out of the path canonicalizer", () => {
    const moniker = toAppsFolderCommand(START_APP_IDS.zoomWithSpaces);
    assert.strictEqual(canonicalizeWin32LaunchCommand(moniker), moniker);
  });
});
