/**
 * The full Lucide set, re-exported by deep path instead of through the package barrel so it can
 * live in its own async chunk. Generated by the `rovyl:lucide-icon-set` plugin in `vite.config.mjs`
 * — see the comment there for why the barrel itself cannot be dynamically imported.
 */
declare module "virtual:lucide-icon-set" {
  import type { LucideIcon } from "lucide-react";
  /**
   * One *named* export per glyph, aliases included (`Globe`, `GlobeIcon`, `LucideGlobe`) — and no
   * default. TypeScript cannot describe "an unknown set of named exports", so the module object is
   * declared as the record it behaves like. Do not add `export default` here: neither branch of
   * the plugin emits one (`export * from "lucide-react"` does not forward a default), so a caller
   * trusting it would read `undefined` at runtime in both dev and the packaged app.
   */
  const iconSet: Record<string, LucideIcon>;
  export = iconSet;
}
